name: Deployment

concurrency: production

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        uses: typst-community/setup-typst@v3.1.0
        with:
          typst-version: latest
      - run: typst compile main.typ jonathan_lopez_resume.pdf
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Resume
          path: jonathan_lopez_resume.pdf
      - name: Download
        uses: actions/download-artifact@v4
        with:
          name: Resume
          path: jonathan_lopez_resume.pdf
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: jonathan_lopez_resume.pdf
