name: Deployment

concurrency: production

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - uses: typst-community/setup-typst@v2.0.1
      - run: typst compile main.typ jonathan_lopez_resume.pdf
      - uses: actions/upload-artifact@v4
        with:
          name: Resume
          path: jonathan_lopez_resume.pdf
      
              
